config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "missions#index"
  resources :users, only: [:show]
  get "dashboard", to: "dashboards#show"
  # shallow: supprime nesté si pas besoin
  resources :missions, only: [:show], shallow: true do
    resources :bookings, only: %i[show create]
  end

  namespace :organisation do
    resources :missions, only: %i[index show new create edit update]
    resources :bookings, only: %i[edit update]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one_attached :photo
  # belongs_to :user
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :mission
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  has_many :bookings

  has_many_attached :photos

  validates :title, :description, :category, :city, :max_participant, :duration, :date, presence: true
  validates :description, length: { minimum: 3 }
  validates :city, format: { with: /[a-zA-Z]/ }
  validate :validate_images
  validate :validate_upload_size

  geocoded_by :address_from_components
  after_validation :geocode, if: :will_save_change_to_address?

  def address_from_components
    "#{address}, #{city}"
  end
  # validate :expiration_date_cannot_be_in_the_past
  # validate :user_an_organisation?, on: :create

  # Ceci est une validation custom
  # Elle permet de creer une mission QUE si organisme = true
  # def user_an_organisation?
  #   user = User.find(user_id)
  #   unless user.organisme
  #     errors.add(:organisme, "Désolé, vous ne pouvez pas creer de mission...")
  #     return false
  #   end
  #   return true
  # end

  # def expiration_date_cannot_be_in_the_past
  #   expiration_date = Mission.find()
  #   if expiration_date.present? && expiration_date < Date.today
  #     errors.add(:expiration_date, "Oups! la date est dans le passé...")
  #   end
  # end

  def past?
    date < Date.today
  end

  def progress
    if past?
      return :past
    else
      return :futur
    end
  end

  private

  def validate_images
    return if photos.count <= 5

    errors.add(:photos, 'Vous pouvez télécharger que 5 photos maximum')
  end

  def validate_upload_size
    photos.each do |photo|
      if photo.blob.byte_size > 10.megabytes
        errors.add(:photos, "La taille de la photo #{photo.blob.filename} est trop grande")
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :missions
  has_many :bookings
  # has_one :badge

  has_one_attached :photo

  validates :firstname, presence: true
  validates :firstname, uniqueness: true

  def badge
    Badge.where("threshold > ?", total_score).first
  end

  def total_score
    # METHODE CLASSIQUE
    # self.bookings.map do |booking|
    #   booking.scoring
    # end.sum
    # METHODE SIMPLIFIEE
    bookings.map(&:scoring).reject(&:nil?).sum.to_i
    # METHODE SIMPLIFIEE ++
    # self.bookings.map(&:scoring).compact.sum.to_i
  end

  def past_missions
    bookings.map(&:mission).select(&:past?)
    # self.bookings.map{|booking| booking.mission}.select{ |mission| mission.past?}
  end

  def futur_missions
    bookings.map(&:mission).reject(&:past?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[firstname photo organisme])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show]

  def new
    @mission = Mission.find(params[:mission_id])
    @booking = Booking.new
  end

  def show
    @mission = @booking.mission
  end

  def create
    # @mission = Mission.find(params[:mission_id])
    @booking = Booking.new(booking_params)
    # @booking.mission = @mission
    @booking.user = current_user
    if @booking.save
      # redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:mission_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    # Je veux acceder aux missions bookée par current user
    @progression = current_user.total_score % 100
    @next_badge = 100 - @progression
  end
end

# Récupérer les missions à venir du current_user (créer des missions + booking)
# Récupérer les missions effectuées du current_user
# Récupérer le score du current_user

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @missions = Mission.all

    @missions = @missions.where("city ILIKE ?", "%#{params[:search][:city]}%") if params.dig(:search, :city).present?
    if params.dig(:search, :category).present?
      @missions = @missions.where("category ILIKE ?", "%#{params[:search][:category]}%")
    end
    @missions = @missions.where(date: params[:search][:date].to_date) if params.dig(:search, :date).present?
    @markers = @missions.geocoded.map do |mission|
      {
        lat: mission.latitude,
        lng: mission.longitude,
        info_window: render_to_string(partial: "info_window", locals: { mission: }),
        image_url: helpers.asset_url("marker.png")
      }
    end
  end

  def show
    @mission = Mission.find(params[:id])
  end
end

app/controllers/organisation/bookings_controller.rb
class Organisation::BookingsController < ApplicationController
  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    # Pas de redirect car on veut rester sur la meme page
    # redirect_to organisation_mission_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:firstname, :scoring)
  end
end

app/controllers/organisation/missions_controller.rb
class Organisation::MissionsController < ApplicationController
  def index
    # Afficher toutes MES missions
    @missions = current_user.missions
  end

  def show
    @mission = Mission.find(params[:id])
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.create(mission_params)
    @mission.user = current_user
    if @mission.save
      redirect_to organisation_mission_path(@mission)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def update
    @mission = Mission.find(params[:id])
    @mission.update(mission_params)
    redirect_to organisation_mission_path(@mission)
  end

  private

  def mission_params
    params.require(:mission).permit(:title, :description, :category, :address, :city, :date, :duration,
                                    :max_participant, :hour, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
  <div class="container-booking-show">
    <div class="row">
        <div class="congrats">
          <h1>Félicitations !<br>Tu es maintenant inscrit(e)!</h1>
          <p>Un membre de Maison de la Nature<br>va t'envoyer les infos de la mission</p>
            <div class="coffee">
            <p><small>Tu peux également participer en faisant un don <br> ou en nous payant un café !</small></p>
              <div class="btn-donation">Je fais un don !
              </div>
          </div>
      </div>
    </div>
  </div>

app/views/dashboards/show.html.erb
<% if current_user.organisme == false %>
<div id="dashboard">
  <div class="container my-3 mx-5">
    <div class="col-8">
      <div class="welcome-dasboard">
        <div class="welcome-avatar-dashboard">
          <% if current_user.photo.key? %>
            <%= cl_image_tag current_user.photo.key, height: 30, width: 40%>
          <% else %>
            <%= image_tag "avatarFemme.jpg", class: "avatar-show" %>
          <% end %>
          <h2>Salut <%= current_user.firstname %> !</h2>
          <small>Bénévole </small>
        </div>
        <h1 class="text-center">MON TABLEAU DE BORD</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="dashboard-body">
      <div class="mission-table">
        <% if current_user.futur_missions.first == nil %>
          <h3>MISSIONS À VENIR:</h3>
          <small class="text-muted font-weight-light">Aucune mission à venir</small>
          <% else %>
          <h3>MISSIONS À VENIR:</h3>
        <% end %>
        <% current_user.futur_missions.each do |mission| %>
        <div class="card-product">
          <% if mission.photos&.first&.key? %>
            <%= cl_image_tag mission.photos.first.key, height: 300, width: 400 %>
          <% else %>
            <img src="<%=image_path('default.jpg')%>" alt="background">
          <% end %>
          <div class="card-product-infos">
            <h2><%= mission.title.capitalize %></h2>
            <p><u>Date</u> :  <%=mission.date.strftime('%d/%m/%Y') %></p>
            <p><u>Heure</u> :  <%=mission.hour %> :00</p>
            <p><u>Lieu de rendez-vous</u> :  <%= mission.address%></p>
            <small>Pour annuler votre présence, merci de contacter directement l'organisme</small>
          </div>
        </div>
        <% end %>
        <% if current_user.past_missions.first == nil%>
          <% else %>
          <h3>MISSIONS PASSÉES:</h3>
        <% end %>
        <% current_user.past_missions.each do |mission| %>
        <div class="card-product opacity-50">
          <% if mission.photos&.first&.key? %>
            <%= cl_image_tag mission.photos.first.key, height: 300, width: 400 %>
          <% else %>
            <img src="<%=image_path('default.jpg')%>" alt="background">
          <% end %>
          <div class="card-product-infos">
            <h2><%= mission.title.capitalize %></h2>
            <p><u>Date</u> :  <%=mission.date.strftime('%d/%m/%Y') %></p>
            <p><u>Heure du rendez-vous</u> :  <%= mission.hour %></p>
            <p><u>Lieu de rendez-vous</u> :  <%= mission.address%></p>
            <small>Pour annuler votre présence, merci de contacter directement l'organisme</small>
          </div>
        </div>
        <% end %>
      </div>
      <div class="score-table">
        <h3 class= "text-center">MON ACTIVITÉ</h3>
        <div id="score">
          <em>Mon score actuel:</em>
          <p><%= current_user.total_score %></p>
        </div>

        <div id="score-calculation">
        <% if current_user.total_score > 1 %>
          <p>Bravo <%= current_user.firstname %>, <br> Continue ton engagement ! Plus que <em><%= @next_badge %> points </em>avant ton prochain badge !</p>
        <% end %>
        </div>
        <div class="score-level">
          <div data-controller="score-animation" data-score-animation-scoring-value="<%=(472-472*0.01*@progression).to_i%>" class="skill">
            <div class="outer">
              <div class="inner">
                <div id="percent_score_number">
                  <%= @progression %>%
                </div>
              </div>
            </div>

            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="160px" height="160px">
                    <defs>
                        <linearGradient id="GradientColor">
                          <stop offset="0%" stop-color="#e91e63" />
                          <stop offset="100%" stop-color="#673ab7" />
                        </linearGradient>
                    </defs>
                    <circle data-score-animation-target="circle" cx="80" cy="80" r="70" stroke-linecap="round"/>
            </svg>
          </div>
        </div>

        <div class="badge-table">
        <% if current_user.total_score > 1%>
          <div class="badge" data-controller="badge" data-badge-target="badge" data-action="mousemove->badge#mousemove">
          <%=render "shared/badges"%>
          </div>
        <% else %>
        <h4>Tu n'as pas encore de badge !</h4>
        <p>Réalise ta première mission pour obtenir ton 1er badge 😍</p>
        <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StandUpForLife</title>
    <link rel="icon" type="img" href="/app/assets/images/logo.png">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Stand Up For Life - Trouves des missions dans ta ville! ">
    <meta property="og:image" content="logo.png">
    <meta property="og:description" content="Stand Up For Life est une plateforme qui te permettra de trouver des missions associatives proche de ta ville">
    <meta property="og:site_name" content="Stand Up For Life"/>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/missions/_info_window.html.erb
<div class="map-mission-infos">
  <h6><%= mission.title %></h6>
  <small class="text-muted"> Durée: <%= mission.duration %> h • <%= mission.category.capitalize %></small>
  <div class="map-mission-infos-location">
      <small class="text-muted">📍 <%=mission.city.capitalize%></small>
      <p class="small"><u> Date</u>:  <%= mission.date.strftime('%d/%m/%Y') %></p>
      <p class="small"><u> Heure</u>:  <%= mission.hour %> :00</p>
  </div>

app/views/missions/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path('banner.jpg')%>);">
    <div class="ban-text">
      <h1>stand up for <span data-controller="typed-js" ></h1></span>
    </div>
    <p> "Il ne peut y avoir de plus grand don que celui de donner son temps et son énergie pour aider les autres sans rien attendre en retour" <small> <em>Nelson Mandela</em> </small>
  <div class="container-form" id= "filter-form">
    <%= simple_form_for(:search, url: root_path, html: { method: :get }) do |f| %>
      <%= f.input :city, class: "form-control",
      input_html: {data: {address_autocomplete_target: "address"}},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
      :placeholder => "Choisis ta ville", :placeholder => "Ville", label: false%>
      <%= f.input :category, selected: "humanitaire 🙏🏻" , as: :select, collection: ["humanitaire 🙏🏻", "environnement 🌱", "animaux 🐶"], label: false %>
      <%= f.input :date, as: :date, html5: true, :placeholder => "Date", label: false %>
      <%= f.submit "Rechercher", class: "btn btn-ghost-white-banner"%>
    <% end %>
  </div>
</div>

<div class="mt-5">
  <div class="body-index">
    <div class="cards-mission col-md-7">
      <% @missions.each do |mission| %>
        <div class="zoom">
            <div class="card-mission m-3 ">
              <div id="<%="carousel-mission-#{mission.id}"%>" class="carousel slide" data-bs-ride="false">

                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <% if mission.photos&.first&.key? %>
                        <%= cl_image_tag mission.photos.first.key, class: "d-block w-100" %>
                      <% else %>
                        <img src="<%=image_path('default.jpg')%>" alt="background", class="d-block w-100" >
                      <% end %>
                    </div>
                    <% mission.photos.drop(1).each do |photo|%>
                      <div class="carousel-item">
                        <%= cl_image_tag photo.key, class: "d-block w-100" %>
                      </div>
                    <% end %>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#<%="carousel-mission-#{mission.id}"%>" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#<%="carousel-mission-#{mission.id}"%>" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>

              </div>
              <%= link_to mission_path(mission) do %>
              <div class="card-mission-infos">
                <h3><%= mission.title %></h3>
                <div class="mb-3">
                  <small class="text-muted"> Durée: <%= mission.duration %> h • <%= mission.category.capitalize %></small>
                </div>
                <div class="card-mission-infos-location">
                  <div>
                    <p class="small"><u>Date</u>:  <%= mission.date.strftime('%d/%m/%Y')  %></p>
                    <p class="small"><u>Heure</u>:  <%= mission.hour %>:00</p>
                  </div>
                  <small class="card-mission-location"> 📍 <%=mission.city.capitalize%></small>
                </div>
                  <p><%= truncate(mission.description, :length => 100)%>Voir plus</p>
                </div>
              </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="geo sticky-top"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/missions/show.html.erb
<div class="container my-3 mx-5">
  <div class="col-5">
    <div class="avatar-flex">
      <% if current_user.photo.key? %>
        <%= cl_image_tag current_user.photo.key, height: 30, width: 40%>
      <% else %>
        <%= image_tag "avatarFemme.jpg", class: "avatar-show" %>
      <% end %>
      <h1><%= @mission.user.firstname %></h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="principale">
      <% if @mission.photos&.first&.key? %>
        <div class="principale-img">
          <%= cl_image_tag @mission.photos.first.key,  height: 400, width: 600 %>
        </div>
        <div class="galery">
          <% @mission.photos.drop(1).each do |photo| %>
            <%= cl_image_tag photo.key %>
          <% end %>
        </div>
      <% else %>
        <img src="<%=image_path('default.jpg')%>" alt="background">
      <% end %>
  </div>
    <div class="title-detail mt-3 mb-5">
      <h2><%= @mission.title.capitalize %></h2>
      <small class="text-muted">Durée:  <%= @mission.duration%> h • <%=@mission.city.capitalize %> • <%= @mission.category %></small>
    </div>
  </div>
</div>

<div class="container">
  <div class="info-participants d-flex justify-content-between mb-5">
    <div class="col-8">
      <div class=" content-details mb-3">
        <p class="m-0"><u>Date</u> : <%= @mission.date.strftime('%d/%m/%Y') %></p>
        <p class="m-0"><u>Heure</u> : <%= @mission.hour %>:00</p>
        <p><u>Lieu de rendez-vous</u> : <%= @mission.address.capitalize %></p>
        <p><%= @mission.description.capitalize%></p>
      </div>
    </div>
      <div class="col-3">
        <div class="info-button">
          <%= simple_form_for([@mission, Booking.new]) do |f| %>
          <%= f.input :mission_id, input_html: {value: @mission.id}, as: :hidden %>
          <%= f.submit "Je participe !", class: "btn btn-participate mb-3", data: {bs_toggle:"modal", bs_target:"#exampleModal"}%>
          <% end %>
        </div>
      </div>
  </div>
</div>


<!-- Button trigger modal -->
<%# <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button> %>

<!-- Modal -->
<div class="modal hide fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">

    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Félicitations !<br>Tu es maintenant inscrit(e) !<br>🎉</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Un membre de Maison de la Nature<br>va t'envoyer les infos de la mission</p>
      </div>
      <div class="modal-footer">
      <p><small>Tu peux également participer en faisant un don <br> ou en nous payant un café ! ☕</small></p>
        <%# <button type="button" class="btn btn-ghost" data-bs-dismiss="modal">Fermer</button> %>
        <%= link_to "Fermer", dashboard_path , class: "btn btn-ghost" %>
        <button type="button" class="btn btn-ghost">Faire un don !</button>
      </div>
    </div>
  </div>
</div>

app/views/organisation/edit.html.erb
<% if current_user.organisme%>
<div class="form-page">
  <div class="container">
      <div class="col-xs-12 col-md-6 col-sm-offset-4 m-auto">
      <div class="form">
      <h1>Modifie ta mission</h1>
        <%= simple_form_for([:organisation, @mission]) do |f| %>
          <%= f.input :title, :label => "Nom de la mission" %>
          <%= f.input :description, :label => "Description de la mission" %>
          <%= f.input :category, as: :select, collection: ["humanitaire 🙏🏻", "environnement 🌱", "animaux 🐶"], :label => " Categorie" %>
          <%= f.input :address, :label => "Lieu du rendez-vous" %>
          <%= f.input :city, :label => "Ville" %>
          <%= f.input :date, html5: true %>
          <%= f.input :hour, as: :time, html5: true, :label => "Heure du rendez-vous"%>
          <%= f.input :duration,:label => "Durée de la mission"  %>
          <%= f.input :max_participant, :label => "Nombre de participant maximum" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "J'ajoute cette mission", class: "btn btn-ghost-white mb-3"%>
        <% end %>
      </div>
  </div>
</div>
<% else %>
<h2 class= "text-center">PAGE NON ACCESSIBLE</h2>
<% end %>

app/views/organisation/missions/show.html.erb
<div class="container my-3 mx-5">
  <div class="col-5">
    <div class="avatar-flex">
      <% if current_user.photo.key? %>
        <%= cl_image_tag current_user.photo.key, height: 30, width: 40%>
      <% else %>
        <%= image_tag "avatarFemme.jpg", class: "avatar-show" %>
      <% end %>
      <h1><%= current_user.firstname %></h1>
    </div>
  </div>
</div>

<div class="container">
  <div class="principale">
      <% if @mission.photos&.first&.key? %>
        <div class="principale-img">
          <%= cl_image_tag @mission.photos.first.key,  height: 400, width: 600 %>
        </div>
        <div class="galery">
          <% @mission.photos.drop(1).each do |photo| %>
            <%= cl_image_tag photo.key %>
          <% end %>
        </div>
      <% else %>
        <img src="<%=image_path('default.jpg')%>" alt="background">
      <% end %>
  </div>
    <div class="title-detail mb-3">
      <div class="fontawsome">
      <%= link_to edit_organisation_mission_path(@mission) do%>
      <i class="fa-solid fa-pen", class="fas fa link"></i>
      <% end %>
          <i class="fa-solid fa-trash"></i>
      </div>
      <h2><%= @mission.title.capitalize %></h2>
      <small class="text-muted">Durée: <%= @mission.duration%> h • <%=@mission.city.capitalize%> • <%=@mission.category %></small>
    </div>
</div>


<div class="container">
  <div class="info-participants d-flex justify-content-between mb-5">
    <div class="col-6">
      <div class=" content-details">
        <p class="m-0"><u>Date</u> : <%= @mission.date.strftime('%d/%m/%Y') %></p>
        <p class="m-0"><u>Heure</u> : <%= @mission.hour %>:00</p>
        <p class="mb-3"><u>Lieu de rendez-vous</u> : <%= @mission.address.capitalize %></p>
        <p><%= @mission.description%></p>
      </div>
    </div>
    <div class="">
      <div class="participants sticky-top">
        <h2>Personnes inscrites:</h2>
        <ol>
          <% @mission.bookings.each do |booking| %>
          <li class = "mt-3">
          <h4><%= booking.user.firstname %></h4>
            <%= simple_form_for :booking, url: organisation_booking_path(booking), method: :patch do |f|%>
              <div class= "d-flex justify-content-between">
                <div class="col-sm-offset-6 col-md-7 m-0">
                  <%= f.input :scoring, as: :numeric, :placeholder => "1h = 10 pts", label: false %>
                </div>
                <div class="col-sm-offset-3 col-sm-3 col-md-4 mx-5">
                  <%= f.button :submit, "#{booking.user.firstname} ✓", class:"btn btn-ghost-white" %>
                </div>
              </div>
              <% if booking.scoring %>
              <small class = "m-0">Vous avez attribué <%= booking.scoring.to_i %> point(s) à <%= booking.user.firstname %></small>
              <% end %>
            <% end %>
          </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item name">
          <%if current_user.organisme == false %>
            <em><%= link_to current_user.firstname, dashboard_path , class: "nav-link" %></em>
          <% else %>
            <em><%= link_to current_user.firstname, organisation_missions_path , class: "nav-link" %></em>
          <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatarFemme.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.organisme%>
                <%= link_to "Gerer mes missions", organisation_missions_path, class: "dropdown-item" %>
                <%= link_to "Créer une mission", new_organisation_mission_path, class: "dropdown-item" %>
              <% end %>
              <%= button_to "Log out", destroy_user_session_path, form: {turbolink: false}, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>